// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
// Berkas konfigurasi otomatis dari FlutterFire CLI berisi API key dan ID project Firebase untuk masing-masing platform.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcfyQEIFrtdeFP0yjkGdtqFH86Zs_PH3o',
    appId: '1:536440430437:web:3170b0eefa611bab614b8c',
    messagingSenderId: '536440430437',
    projectId: 'palembang-5f717',
    authDomain: 'palembang-5f717.firebaseapp.com',
    storageBucket: 'palembang-5f717.firebasestorage.app',
    measurementId: 'G-NQDEX58373',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3W_PuTvnzCtA4vU2B5LZ3oDEg_z_uOvE',
    appId: '1:536440430437:android:748c82969f856059614b8c',
    messagingSenderId: '536440430437',
    projectId: 'palembang-5f717',
    storageBucket: 'palembang-5f717.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAg37GadnmHbD-lQhWePUHPh3yGjHc2OdY',
    appId: '1:536440430437:ios:1fd1f8b21618f1b1614b8c',
    messagingSenderId: '536440430437',
    projectId: 'palembang-5f717',
    storageBucket: 'palembang-5f717.firebasestorage.app',
    iosBundleId: 'com.example.cafeProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAg37GadnmHbD-lQhWePUHPh3yGjHc2OdY',
    appId: '1:536440430437:ios:1fd1f8b21618f1b1614b8c',
    messagingSenderId: '536440430437',
    projectId: 'palembang-5f717',
    storageBucket: 'palembang-5f717.firebasestorage.app',
    iosBundleId: 'com.example.cafeProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDcfyQEIFrtdeFP0yjkGdtqFH86Zs_PH3o',
    appId: '1:536440430437:web:2010c986ba09dcfd614b8c',
    messagingSenderId: '536440430437',
    projectId: 'palembang-5f717',
    authDomain: 'palembang-5f717.firebaseapp.com',
    storageBucket: 'palembang-5f717.firebasestorage.app',
    measurementId: 'G-4TCLQCF77H',
  );

}